---
title: "Learn-GenAI: summary"
lang: en
author: AP 
format:
  revealjs: 
    theme: solarized
    css: ../styles/dsta_slides.css
    slide-number: true
    slide-level: 2
    # title-slide-attributes:
      # data-background-image: ../../styles/bbk-logo.svg
    code-fold: false
    echo: true
    # smaller: true
    # scrollable: true
  html:
    toc: true
    code-fold: false
    anchor-sections: true
    other-links:
      - text: Class page
        href: https://github.com/ale66/learn-genai
jupyter: python3
#engine: knitr
---

# Summary

## Artificial Intelligence

- McCarthy: replication of the principles of reasoning with a logical representation and computer reasoning

- Minsky: replication of the neurological architecture (the neural network) and of its decentralisation
  
Generative AI applies Minsky's approach with a neural network at its core



## NLP

- only word occurrences count

- neural networks have weighted connections

- NNs and most Gen AI solutions start with a random weights allocation and require training to refine weights and become effective


## Information Entropy

- measures over $[0..\log n]$ the expectation of content (surprise) embedded in a word frequency distribution

- *perplexity* an entropy-based measure of possible phrase continuations


## Further topics

- Vectorisation

- The Encoder/Decoder architectural view

- Encoding only: BERT

- fine tuning
  - low-ranking: LoRa
  - RAG

- the attention mechanism


## Lecture plan

- Entropy-based NLP; phrase continuations and perplexity

- Notebook: LoRa/fine-tuning for visual and narrative voices
  
- Vectorisation

- Notebook: build your own RAG

- An introduction to attention

- Notebook: the attention mechanism
