---
title: "Entropy: a summary"
lang: en
author: AP 
format:
  revealjs: 
    theme: solarized
    css: ../styles/dsta_slides.css
    slide-number: true
    slide-level: 2
    # title-slide-attributes:
      # data-background-image: ../../styles/bbk-logo.svg
    code-fold: false
    echo: true
    # smaller: true
    # scrollable: true
  html:
    toc: true
    code-fold: false
    anchor-sections: true
    other-links:
      - text: Class page
        href: https://github.com/ale66/learn-genai
jupyter: python3
#engine: knitr
---

# Summary

## GenAI today

- a complex operation that generates text (mostly)

- at the core, a neural net: a mesh of artificial neurons 
  
- neurons and connections are all *weighted*

## Minsky's vision

- the biological neuron is the basis of animal intelligence

- if a human with neurons can learn language then a computer with neurons also should

- neurons underpin *memory,* memory underpins learning  

## Gabriele's vision

- Chatbots are a complex, multi-part Big Data architecture

- neural nets sit at their centre, providing the memory and generation part

- it's all about weights assigned to neural connections: learning is weight refinement

-----

- the more neurons/weights there are, the better (1B, 2B ...)

- setting the weights is a big training operation

- so, different from humans, Chatbots have their learning stopped at some point

- long, modular prompts supply a *context* for the generative part 


# Further...

- the neural net *learns* by adjusting its weights to better capture the examples given to *train* it

- quantity and quality of the examples impact the weight thus the quality of the learning

- weights, as in 'open weights,' are the core of the core of GenAI systems


## Quantity

Perhaps surprisingly, weights are initialised to random values: 

it takes *extensive training* to adjust the weights towards a stable, effective set of values

The sheer amount of text that is used for learning is a huge factor but perhaps less important going forward


## Quality

The diversity of the text used in training is a huge factor

The intrinsic quality of a training text is often assessed using *information entropy*


## Information Entropy

Information entropy is a value between 0 and $\log n$.

Low entropy: text is deterministic: words/syntagmas are recurrent (ex.: Frankie Hi NRG) generation will be as non-diversified as the training

High entropy: all combinations come about, little learning as there is low discriminating value